# Generated by Django 5.2.6 on 2025-11-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this prescription entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_image',
            field=models.ImageField(blank=True, help_text='Scanned or photographed prescription', null=True, upload_to='prescriptions/%Y/%m/%d/'),
        ),
    ]
