# Generated by Django 5.2.6 on 2025-11-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_prescription_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_image',
            field=models.FileField(blank=True, help_text='Scanned or photographed prescription (images or PDF)', null=True, upload_to='prescriptions/%Y/%m/%d/'),
        ),
    ]
