# Generated by Django 5.2.6 on 2025-11-20 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_expenseentry_revenueentry'),
        ('patients', '0004_alter_prescription_prescription_image'),
    ]

    def nullify_prescriptions(apps, schema_editor):
        Invoice = apps.get_model('Finance', 'Invoice')
        Invoice.objects.update(prescription=None)

    operations = [
        migrations.RunPython(nullify_prescriptions),
        migrations.AlterField(
            model_name='invoice',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='patients.prescription'),
        ),
    ]
