# Generated by Django 5.2.6 on 2025-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='User must change password on next login'),
        ),
    ]
