<template>
	<div class="card" style="max-width:520px;">
		<h3>New Patient</h3>
		<form @submit.prevent="save">
			<label>Name *</label>
			<input v-model="form.name" required />
			
			<label>Username *</label>
			<input v-model="form.username" required placeholder="Unique username" />
			
			<label>DOB</label>
			<input v-model="form.dob" type="date" />
			
			<label>Gender</label>
			<select v-model="form.gender">
				<option value="">--</option>
				<option value="M">Male</option>
				<option value="F">Female</option>
				<option value="O">Other</option>
			</select>
			
			<label>National ID</label>
			<input v-model="form.national_id" maxlength="20" placeholder="e.g. 12345678" />
			<small style="color:#666; display:block; margin-top:4px;">Optional but recommended for patient verification.</small>
			
			<label>Contact</label>
			<input v-model="form.contact" />
			
			<small style="color:#666; display:block; margin-top:-0.5rem; margin-bottom:1rem;">Medical ID will be auto-generated by the system.</small>
			
			<button :disabled="saving">{{ saving ? 'Saving...' : 'Create' }}</button>
			<p v-if="err" style="color:red; margin-top:.5rem;">{{ err }}</p>
		</form>
	</div>
</template>

<script setup>
import { reactive, ref } from "vue";
import { useRouter } from "vue-router";
import api from "../api/client";

const router = useRouter();
const form = reactive({ name:"", username:"", dob:"", gender:"", contact:"", national_id:"" });
const err = ref(""); const saving = ref(false);

async function save() {
	err.value = ""; saving.value = true;
	try {
		const payload = { ...form };
		if (!payload.national_id?.trim()) {
			delete payload.national_id;
		} else {
			payload.national_id = payload.national_id.trim();
		}
		await api.post("/api/patients/", payload);
		router.push({ name: "PatientsList" });
	} catch (e) {
		err.value = e?.response?.data ? JSON.stringify(e.response.data) : "Failed";
	} finally {
		saving.value = false;
	}
}
</script>
