# Generated by Django 5.2.6 on 2025-11-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISPENSED', 'Dispensed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
