# Generated by Django 5.2.6 on 2025-11-12 11:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_prescription_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='unit_price',
            new_name='buying_price',
        ),
        migrations.AddField(
            model_name='medicine',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
