# Generated by Django 5.2.6 on 2025-11-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_prescriptiondispense_additional_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondispense',
            name='additional_charges_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
