# Generated by Django 5.2.6 on 2025-11-20 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_prescription_prescription_image'),
        ('pharmacy', '0005_prescriptiondispense_additional_charges_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='patients.prescription'),
        ),
        migrations.AlterField(
            model_name='prescriptiondispense',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_record', to='patients.prescription'),
        ),
    ]
